spring.application.name=udtale

spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb://localhost/udtale

spring.docker.compose.enabled=false

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.chat.options.max-tokens=4096
