spring.application.name=udtale

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

spring.data.mongodb.auto-index-creation=true


spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.chat.options.max-tokens=4096

logging.level.root=DEBUG
logging.level.org.springframework=DEBUG
